### ISSUE TITLE
`-sectcreate __DATA` does not work in xtools' `ld64`

### ISSUE THREAD

**Issue by barracuda156** [iains/darwin-xtools#22]
@iains Binary embedding does not work with `ld64` from `xtools`, but works fine with `ld64-97`. This is rarely relevant, but I had to use it in one port, where original Linux solution did not work for macOS. It worked fine earlier, but failed now: turned out, due to `xtools` linker. Switching to `ld64-97` fixed the problem.

Error:
```
[ 98%] Building C object CMakeFiles/utox.dir/src/window.c.o
/opt/local/bin/gcc-mp-14  -I/opt/local/include -isystem /opt/local/var/macports/build/uTox-5504fd56/work/uTox/third_party/stb/. -isystem /opt/local/var/macports/build/uTox-5504fd56/work/uTox/third_party/minini/minini/dev -isystem /opt/local/var/macports/build/uTox-5504fd56/work/uTox/third_party/qrcodegen/qrcodegen/c -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -Wall -Wextra -Wpointer-arith -Wimplicit-fallthrough=5 -Werror=implicit-function-declaration -Wformat=0 -Wno-misleading-indentation -fno-strict-aliasing -fPIC -fno-common -std=gnu11 -arch ppc -mmacosx-version-min=10.6 -MD -MT CMakeFiles/utox.dir/src/window.c.o -MF CMakeFiles/utox.dir/src/window.c.o.d -o CMakeFiles/utox.dir/src/window.c.o -c /opt/local/var/macports/build/uTox-5504fd56/work/uTox/src/window.c
[100%] Linking C executable utox
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/utox.dir/link.txt --verbose=ON
Undefined symbols for architecture ppc:
  "__section$__DATA__icons_utox_png", referenced from:
      _draw_tray_icon in libutoxNATIVE.a(tray.c.o)
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
/opt/local/bin/gcc-mp-14 -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -Wall -Wextra -Wpointer-arith -Wimplicit-fallthrough=5 -Werror=implicit-function-declaration -Wformat=0 -Wno-misleading-indentation -fno-strict-aliasing -fPIC -fno-common -arch ppc -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -sectcreate __DATA __icons_utox_png /opt/local/var/macports/build/uTox-5504fd56/work/uTox/icons/utox.png CMakeFiles/utox.dir/src/avatar.c.o CMakeFiles/utox.dir/src/chatlog.c.o CMakeFiles/utox.dir/src/chrono.c.o CMakeFiles/utox.dir/src/command_funcs.c.o CMakeFiles/utox.dir/src/commands.c.o CMakeFiles/utox.dir/src/devices.c.o CMakeFiles/utox.dir/src/file_transfers.c.o CMakeFiles/utox.dir/src/filesys.c.o CMakeFiles/utox.dir/src/flist.c.o CMakeFiles/utox.dir/src/friend.c.o CMakeFiles/utox.dir/src/groups.c.o CMakeFiles/utox.dir/src/inline_video.c.o CMakeFiles/utox.dir/src/logging.c.o CMakeFiles/utox.dir/src/main.c.o CMakeFiles/utox.dir/src/messages.c.o CMakeFiles/utox.dir/src/notify.c.o CMakeFiles/utox.dir/src/qr.c.o CMakeFiles/utox.dir/src/screen_grab.c.o CMakeFiles/utox.dir/src/self.c.o CMakeFiles/utox.dir/src/settings.c.o CMakeFiles/utox.dir/src/text.c.o CMakeFiles/utox.dir/src/theme.c.o CMakeFiles/utox.dir/src/theme_tables.c.o CMakeFiles/utox.dir/src/tox.c.o CMakeFiles/utox.dir/src/tox_callbacks.c.o CMakeFiles/utox.dir/src/ui.c.o CMakeFiles/utox.dir/src/ui_i18n.c.o CMakeFiles/utox.dir/src/utox.c.o CMakeFiles/utox.dir/src/window.c.o -o utox  -Wl,-rpath,/opt/local/lib src/av/libutoxAV.a src/xlib/libutoxNATIVE.a src/ui/libutoxUI.a /opt/local/lib/libtoxcore.dylib /opt/local/lib/libsodium.dylib /opt/local/lib/libvpx.dylib -lpthread -lm third_party/stb/libstb.a third_party/minini/libminini.a third_party/qrcodegen/libqrcodegen.a /opt/local/lib/libopus.dylib /opt/local/lib/libfontconfig.dylib /opt/local/lib/libSM.dylib /opt/local/lib/libICE.dylib /opt/local/lib/libX11.dylib /opt/local/lib/libXext.dylib /opt/local/lib/libXrender.dylib /opt/local/lib/libfreetype.dylib /opt/local/lib/libdbus-1.dylib -framework OpenAL src/layout/libutoxLAYOUT.a
make[2]: *** [utox] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/uTox-5504fd56/work/build'
make[1]: *** [CMakeFiles/utox.dir/all] Error 2
make[1]: Leaving directory `/opt/local/var/macports/build/uTox-5504fd56/work/build'
make: *** [all] Error 2
```

What the code was doing:
```
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -380,9 +382,16 @@ target_link_libraries(utox
     qrcodegen
 )
 
+if(APPLE AND NOT ENABLE_COCOA)
+    target_link_options(utox
+        PRIVATE
+        -sectcreate __DATA __icons_utox_png ${CMAKE_SOURCE_DIR}/icons/utox.png
+    )
+endif()
+
 set_property(TARGET utox PROPERTY C_STANDARD 11)
 
--- src/xlib/tray.c
+++ src/xlib/tray.c
@@ -14,9 +14,8 @@
 #include <stdlib.h>
 #include <string.h>
 
-// Converted to a binary and linked at build time
-extern uint8_t _binary_icons_utox_128x128_png_start;
-extern uint8_t _binary_icons_utox_128x128_png_end;
+/* Converted to a binary and linked at build time */
+EXTLD(icons_utox_png)
 
 static void send_message(Display *dpy, /* display */
                   Window w, /* sender (tray window) */
@@ -93,8 +92,8 @@ static void draw_tray_icon(void) {
     LOG_NOTE("XLib Tray", "Draw Tray");
 
     uint16_t width, height;
-    uint8_t *icon_data = &_binary_icons_utox_128x128_png_start;
-    size_t   icon_size = &_binary_icons_utox_128x128_png_end - &_binary_icons_utox_128x128_png_start;
+    uint8_t *icon_data = LDVAR(icons_utox_png);
+    size_t   icon_size = LDLEN(icons_utox_png);
 
     NATIVE_IMAGE *icon = utox_image_to_native(icon_data, icon_size, &width, &height, 0);
     if (NATIVE_IMAGE_IS_VALID(icon)) {
diff --git src/xlib/tray.h src/xlib/tray.h
index 6e24c77d..45a92862 100644
--- src/xlib/tray.h
+++ src/xlib/tray.h
@@ -21,4 +21,34 @@ void destroy_tray_icon(void);
 
 bool tray_window_event(XEvent *event);
 
+#ifdef __APPLE__
+#include <mach-o/getsect.h>
+
+#define EXTLD(NAME) \
+    extern uint8_t _section$__DATA__ ## NAME [];
+#define LDVAR(NAME) _section$__DATA__ ## NAME
+#define LDLEN(NAME) (getsectbyname("__DATA", "__" #NAME)->size)
+
+#elif (defined __WIN32__)  /* mingw */
+
+#define EXTLD(NAME) \
+    extern uint8_t binary_ ## NAME ## _start[]; \
+    extern uint8_t binary_ ## NAME ## _end[];
+#define LDVAR(NAME) \
+    binary_ ## NAME ## _start
+#define LDLEN(NAME) \
+    ((binary_ ## NAME ## _end) - (binary_ ## NAME ## _start))
+
+#else /* gnu/linux ld */
+
+#define EXTLD(NAME) \
+    extern uint8_t _binary_ ## NAME ## _start[]; \
+    extern uint8_t _binary_ ## NAME ## _end[];
+#define LDVAR(NAME) \
+    _binary_ ## NAME ## _start
+#define LDLEN(NAME) \
+    ((_binary_ ## NAME ## _end) - (_binary_ ## NAME ## _start))
+
+#endif
+
 #endif
```
With `ld64-97` the same code works, linking succeeds.

**Comment by iains** [comment]
hmm ... OK... needs investigation - does this only apply to powerpc - or does it also fail for i686?

I believe that section symbols should be working (they are used by D, which is one of the reasons I use xtools-0.7.0 for building on 10.5)

**Comment by iains** [comment]
AFAICT the section is being added correctly (i.e. the issue is with the symbol or irs spelling).
 
But... I also see the reported problem with standard Apple linkers from 10.7+ ... i.e. this seems only to work on ld64-97.17 and the logic changed somewhat after that.

What does this package do with clang on later OS versions?

I wonder if
```
uintptr_t a = (getsectbyname("__DATA", "__" #NAME)->addr);
```
Would just DTRT?

**Comment by barracuda156** [comment]
@iains I have to check that. Build logs are gone, but we know that on x86 the port failed on < 10.12 and worked on later systems: https://ports.macports.org/port/uTox/details (10.12 threshold suggests some common legacy-support issue but we don’t know if ld also failed or not).

**Comment by iains** [comment]
**I think that the issue here is not with the linker, but the code ... (and I am very surprised that anyone thinks it works on any version of the OS, since I have tested what's below on 10.6, 10.7, 10.10, 10.11..15 macOS 11, 12, 14 and 15 using the _system_ tools and the behaviour is completely consistent)** 

Background:

macOS ld will synthesise a section start symbol when it sees an undefined reference to one.
The form of the symbol is `section$start$<segment>$<section>`

NOTE:
 * this symbol includes '$' characters which are _not_ part of the C or C++ (up to C++23) standards.  Thus putting them in an external reference is an extension (supported by GCC and clang). Usually this is done to avoid potential clashes with user symbols (the argument is that if the user makes use of an extension they cannot complain if there's a clash with a system-provided resource).
 * the symbol checked by ld **_does not_** include the starting '_' which is added to global symbols by the compilers.

so in this code...

```
#include <stddef.h>
#include <mach-o/getsect.h>

extern const char section$start$__DATA$__icon_data [];
extern const char section$end$__DATA$__icon_data [];

int main ()
{
   const char *icon_data = section$start$__DATA$__icon_data;
   const char *icon_end = section$end$__DATA$__icon_data;

   size_t s = (getsectbyname("__DATA", "__icon_data")->size);
   __builtin_printf("addr %p, end %p, size is %ld\n",
		    (void *)icon_data, (void *)icon_end, s);
   return 0;
}

```

The object file will contain `_section$start$__DATA$__icon_data`
but the linker is looking for `section$start$__DATA$__icon_data`

And so it will fail to synthesise the required symbol leading to the fails we see,

** However ... there is a way to do this from C and C++**

```

#include <stddef.h>
#include <mach-o/getsect.h>

extern const char icon_data[] __asm__("section$start$__DATA$__icon_data") ;
extern const char icon_end[] __asm__("section$end$__DATA$__icon_data") ;

int main ()
{
   size_t s = (getsectbyname("__DATA", "__icon_data")->size);
   __builtin_printf("addr %p, end %p, size is %ld\n",
		    (void *)icon_data, (void *)icon_end, s);
   return 0;
}

```

There does seem to be some special case for `_section$<segment><section>` in ld97.17 - but this is not really useful, since it does not work on any other version - you need to pick a more portable mechanism like above.

Of course, we could fix up `xtools` to recognise the `_section$start$__DATA$__icon_data` version, but this does not seem to be a bug, and we would be adding a feature that then would not be portable to the system tools.

NOTE: I have __*not*__ tested 10.5 .. AFAIR the system linker [85.2.1] does not support this which is why I use xtools-0.7.0 always there, to support D which also uses these section symbols.

**Comment by iains** [comment]
I wrote:
    There does seem to be some special case for `_section$<segment><section>` in `ld64-97.17` - but this is not really useful, since it does not work on any other version - you need to pick a more portable mechanism like above.

-- this corresponds to section symbols added for each section by ld64-85.2.1 and ld64-97.17, but no longer supported after that.  So the comment about needing to use the modern version for forward-compatibility/portability does apply.

I wrote:
    NOTE: I have not tested 10.5 .. AFAIR the system linker [85.2.1] does not support this which is why I use xtools-0.7.0 always there, to support D which also uses these section symbols.

I checked the sources, and memory is correct - ld64-85.2.1 does not support the modern version, so I will stick to using xtools-0.7.0 for that.

**Comment by barracuda156** [comment]
Thank you very much, Iain. So we can close the issue, no changes needed, right? I will fix the patch for `uTox` to use the code version you suggested above.

**Comment by iains** [comment]
yeah ... this can be closed, the solution above should work for all supported macOS versions when using xtools-0.7.0 or a later linker.
